services:
  streetcode-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: streetcode-db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "${MS_SQL_DB_PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      
    container_name: streetcode-backend
    restart: unless-stopped
    environment:
      - STREETCODE_CORS__AllowedOrigins__0=http://localhost:3000
      - STREETCODE_CORS__AllowedOrigins__1=http://${HOST_IP}:3000
      - ASPNETCORE_ENVIRONMENT=Local
      - STREETCODE_ConnectionStrings__DefaultConnection=Server=streetcode-db,1433;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=true;Connect Timeout=60;
    depends_on:
      streetcode-db:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
    container_name: streetcode-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mssql_data: